package env

import "os"

var (
	AWS_ACCESS_KEY_ID = os.Getenv("AWS_ACCESS_KEY_ID")
	AWS_ACCESS_KEY_SECRET = os.Getenv("AWS_ACCESS_KEY_SECRET")
	AWS_REGION = os.Getenv("AWS_REGION")
	MONGO_HOST = os.Getenv("MONGO_HOST")
	MONGO_USERNAME = os.Getenv("MONGO_USERNAME")
	MONGO_PASSWORD = os.Getenv("MONGO_PASSWORD")
	MONGO_DATABASE = os.Getenv("MONGO_DATABASE")
	MONGO_ALBUM_COLLECTION = os.Getenv("MONGO_ALBUM_COLLECTION")
	MONGO_IMAGE_COLLECTION = os.Getenv("MONGO_IMAGE_COLLECTION")
	MONGO_VIDEO_COLLECTION = os.Getenv("MONGO_VIDEO_COLLECTION")
)