name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: DockerHub - Build & Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            reclyptor/turrium:latest
            reclyptor/turrium:${{ github.sha }}

      - name: Azure - Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: turrium
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: reclyptor/turrium:${{ github.sha }}

      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}